### ISSUE TITLE
On some operating systems no error is logged when an `omrelp` action fails to process a log entry

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener-extension-shoot-rsyslog-relp#3]
**What happened**:
On some operating systems, when an rsyslog [`omrelp` action](https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/d59c9bccf67d4ed9ae827338748e8ea57bf8ec69/charts/internal/rsyslog-relp-configurator/templates/configmap.yaml#L101C1-L129) fails while processing a log entry, nothing about this failure is logged and no further logs are processed. This seems to happen on gardenlinux `943.9` and suse-chost `15 SP3 20230613` where the version of librelp is `0.5.1`.
This problem does not happen on suse-chost `15 SP4 20230510` where the version of librelp is `0.3.0`.

**What you expected to happen**:
Errors from `omrelp` actions to be logged properlly so that they can be collected in gardener's logging satck.

**How to reproduce it (as minimally and precisely as possible)**:
1. Make sure that the `gardener-extension-shoot-rsyslog-relp` extension is installed in your landscape.
2. Create a shoot cluster with 2 nodes: gardenlinux version `943.9` and suse-chost version `15 SP3 20230613`.
3. Configure the extension in your shoot by adding this example configuration to the shoot's `.spec.extensions` array and making sure that the target server `some.rsyslog-rlep.server` doesn't exist:
    ```yaml
    extensions:
    - type: shoot-rsyslog-relp
      providerConfig:
        apiVersion: rsyslog-relp.extensions.gardener.cloud/v1alpha1
        kind: RsyslogRelpConfig
        target: some.rsyslog-rlep.server
        port: 10250
        loggingRules:
        - severity: 7
    ```
4. After the shoot is reconciled, ssh into the shoot's nodes and observe that `journalctl -u rsyslog` displays no errors and that the following command shows that only 1 omrelp action has been processed:
    ```bash
    cat /var/log/rsyslog-stats.log | grep omrelp

    Thu Aug 17 14:57:42 2023: action-0-omrelp: origin=core.action processed=1 failed=0 suspended=0 suspended.duration=0 resumed=0
    ```

**Anything else we need to know**:
According to the [rsyslog action parameters documentation](https://www.rsyslog.com/doc/master/configuration/actions.html#general-action-parameters) a special parameter - `action.errorfile` can be added to the `omrelp` action so that such errors are logged to the file specified in the parameter. This approach has to be evaluated whether it is enough to resolve this issue.

**Environment**:
gardener-extension-shoot-rsyslog-relp version: `v0.1.0`
gardenlinux version: `943.9`
suse-chost version: `15 SP3 20230613`
